apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstoneap
  labels: 
    app: capstoneap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: capstoneap
  template:
    metadata:
      labels:
        app: capstoneap
        role: rolling-update
    spec:
      containers:
      - name: capstoneap
        image: asitpant80/capstoneap:1.0.0
        imagePullPolicy: "Always"
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
