# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1

orbs:
  docker: circleci/docker@1.6.0
    
jobs:
  build:
    docker:
      # Use the same Docker base as the project
      - image: cimg/python:3.7.11-node
          
    working_directory: ~/repo
    
    steps:
      - checkout
      - run:
          name: Create vitual environment
          command: |
            # Create virtual environment
            python3 -m venv ~/.$PROJECT_NAME
            source ~/.$PROJECT_NAME/bin/activate
      - run:
          name: Install dependencies
          command: |            
            # install npm, htmllint
            sudo npm install -g htmllint-cli
            sudo htmllint init
            
            # Install hadolint
            make install-hadolint
      - run:
          name: run lint
          command: |
            source ~/.$PROJECT_NAME/bin/activate
            # make lint for Docker file and index.html
            make lint
workflows:
  default:
    jobs:
      - build
